### ISSUE TITLE
function 'mexcubature_nop' is not defined

### ISSUE THREAD

**Issue by sairamgeethanath** [thanospol/MARIE#2]
Generating the N Operator
Analyzing and transferring files to the workers ...done.
Error using assembly_nop>(parfor body) (line 55)
An UndefinedFunction error was thrown on the workers for 'mexcubature_nop'.  This might be because the file containing
'mexcubature_nop' is not accessible on the workers.  Use addAttachedFiles(pool, files) to specify the required files to
be attached.  See the documentation for 'parallel.Pool/addAttachedFiles' for more details.

Error in assembly_nop (line 49)
parfor mx = 1:L

Error in getOPERATORS (line 82)
        [opToeplitz] = assembly_nop(r,ko,dx,'DIRECTFN');

Error in fVIEsolver_Assembly (line 116)
    [fN] = getOPERATORS(rnew,freq,'N');

Error in VSIE_Solver (line 109)
[fVIEsolver,Gram,tau3,Scoord,dev] = fVIEsolver_Assembly(RHBM,freq,gpu_flag);

Error in MR_Solver (line 267)
                [Zparam,Jcoil,Jbody] = VSIE_Solver(RHBM,COIL,ff,tol,coup,gpu_flag,factorized,tolfactor,blockSize);

Error in MARIE_SolveMR>Solve_Button_Callback (line 283)
[ZP,Jc,Jb,Sb,Eb,Bb,Gsar,Pabs] = MR_Solver(RHBM,COIL,fvalues,tol,flags);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MARIE_SolveMR (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)MARIE_SolveMR('Solve_Button_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    Undefined function 'mexcubature_nop' for input arguments of type 'double'.
 
Error using waitfor
Error while evaluating uicontrol Callback  

Could you please tell us how to solve this problem? @ shahla400@gmail.com

**Comment by jecs** [comment]
It sounds like you either don't have the pertinent subdirectories in your path or you have not compiled the mex function in question. There is a compilation script in the root folder.
